#!/usr/bin/env node
// CRABDEN - turn the uploaded character sheets into a game-sized atlas.
//
//   node tools/sheets.mjs
//
// The sheets are high-resolution and were drawn by a generator, so they carry
// detail that falls apart under scrutiny. Downsampling them hard and snapping
// the result to a small shared palette is not a compromise - it is what makes
// them sit next to the rest of the game's art, and it buries the artefacts.
//
// Produces js/art/people.js: one packed PNG as a data URI plus a frame map.

import pw from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const SHEETS = [
  {
    id: 'vess', file: 'assets/sheet-vess.png', bodyH: 68, colors: 76,
    // band -> the animations packed into it, in order, with frame counts
    bands: [
      [['idleFront', 5], ['idleSide', 5], ['idleBack', 4]],
      [['walkRight', 7], ['walkLeft', 7]],
      [['sit', 5], ['talk', 4], ['command', 2]],
      [['wander', 5], ['interact', 4], ['tired', 2]],
      [['face', 8], ['prop', 7]],
    ],
    faceBands: [4],
  },
  {
    id: 'elder', file: 'assets/sheet-elder.png', bodyH: 74, colors: 64,
    bands: [
      [['idleFront', 3], ['idleSide', 3], ['idleBack', 3]],
      [['walkRight', 7], ['walkLeft', 7]],
      [['sit', 5], ['talk', 4]],
      [['wander', 5], ['interact', 3]],
    ],
    faceBands: [],
  },
];

const browser = await pw.chromium.launch({
  executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  args: ['--no-sandbox'],
});
const page = await browser.newPage();

const out = {};
for (const sheet of SHEETS) {
  const b64 = fs.readFileSync(path.join(root, sheet.file)).toString('base64');
  const res = await page.evaluate(slice, { b64, sheet });
  out[sheet.id] = res;
  console.log(`${sheet.id}: ${res.frameCount} frames, atlas ${res.w}x${res.h}, ` +
    `${(res.png.length * 0.75 / 1024).toFixed(0)}kb`);
  for (const [k, v] of Object.entries(res.frames)) console.log(`   ${k}: ${v.length}`);
}
await browser.close();

const mod = `// CRABDEN - character atlases, generated by tools/sheets.mjs. Do not edit.
//
// The source sheets live in assets/. They are downsampled hard and snapped to a
// small palette on the way in, which is what lets hand-drawn characters stand
// next to procedurally painted ones without either looking out of place.

const DATA = {
${Object.entries(out).map(([id, r]) => `  ${id}: {
    w: ${r.w}, h: ${r.h},
    png: '${r.png}',
    frames: ${JSON.stringify(r.frames)},
  },`).join('\n')}
};

const sheets = {};
let readyResolve;
export const peopleReady = new Promise((r) => { readyResolve = r; });
export const PEOPLE = sheets;

/** Decode every atlas once. Call before the first frame is drawn. */
export function loadPeople() {
  const jobs = Object.entries(DATA).map(([id, d]) => new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const c = document.createElement('canvas');
      c.width = d.w; c.height = d.h;
      const g = c.getContext('2d');
      g.imageSmoothingEnabled = false;
      g.drawImage(img, 0, 0);
      sheets[id] = { canvas: c, frames: d.frames };
      resolve();
    };
    img.onerror = () => { sheets[id] = { canvas: null, frames: d.frames }; resolve(); };
    img.src = d.png;
  }));
  return Promise.all(jobs).then(() => { readyResolve(sheets); return sheets; });
}

/** One frame: { x, y, w, h, ax, ay } in atlas pixels, ax/ay the anchor. */
export function frame(sheet, anim, i = 0) {
  const s = sheets[sheet];
  if (!s) return null;
  const list = s.frames[anim];
  if (!list || !list.length) return null;
  return list[((i % list.length) + list.length) % list.length];
}

export function frameCount(sheet, anim) {
  const s = sheets[sheet];
  return s && s.frames[anim] ? s.frames[anim].length : 0;
}

/** Draw a frame with its anchor on (x, y). */
export function drawFrame(ctx, sheet, anim, i, x, y, flip = false, scale = 1) {
  const s = sheets[sheet];
  if (!s || !s.canvas) return false;
  const f = frame(sheet, anim, i);
  if (!f) return false;
  ctx.save();
  ctx.translate(x, y);
  if (scale !== 1) ctx.scale(scale, scale);
  if (flip) ctx.scale(-1, 1);
  ctx.drawImage(s.canvas, f.x, f.y, f.w, f.h, -f.ax, -f.ay, f.w, f.h);
  ctx.restore();
  return true;
}
`;
fs.writeFileSync(path.join(root, 'js/art/people.js'), mod);
console.log(`wrote js/art/people.js (${(mod.length / 1024).toFixed(0)}kb)`);

// ---------------------------------------------------------------------------

async function slice({ b64, sheet }) {
  const img = new Image();
  img.src = 'data:image/png;base64,' + b64;
  await img.decode();
  const W = img.width, H = img.height;
  const src = document.createElement('canvas');
  src.width = W; src.height = H;
  const sx = src.getContext('2d', { willReadFrequently: true });
  sx.drawImage(img, 0, 0);
  const d = sx.getImageData(0, 0, W, H).data;

  // -- background from the border ------------------------------------------
  const counts = new Map();
  const bump = (i) => {
    const k = (d[i * 4] >> 3 << 10) | (d[i * 4 + 1] >> 3 << 5) | (d[i * 4 + 2] >> 3);
    counts.set(k, (counts.get(k) || 0) + 1);
  };
  for (let X = 0; X < W; X++) { bump(X); bump((H - 1) * W + X); }
  for (let Y = 0; Y < H; Y++) { bump(Y * W); bump(Y * W + W - 1); }
  let best = 0, bk = 0;
  for (const [k, v] of counts) if (v > best) { best = v; bk = k; }
  const bg = [((bk >> 10) & 31) << 3, ((bk >> 5) & 31) << 3, (bk & 31) << 3];

  const mask = new Uint8Array(W * H);
  for (let i = 0; i < W * H; i++) {
    const dr = d[i * 4] - bg[0], dg = d[i * 4 + 1] - bg[1], db = d[i * 4 + 2] - bg[2];
    if (dr * dr + dg * dg + db * db > 34 * 34 && d[i * 4 + 3] > 40) mask[i] = 1;
  }

  // -- connected components -------------------------------------------------
  const lab = new Int32Array(W * H).fill(-1);
  const boxes = [];
  const stack = [];
  for (let s = 0; s < W * H; s++) {
    if (!mask[s] || lab[s] >= 0) continue;
    const id = boxes.length;
    let x0 = W, y0 = H, x1 = 0, y1 = 0, area = 0;
    stack.push(s); lab[s] = id;
    while (stack.length) {
      const p = stack.pop();
      const py = (p / W) | 0, pxx = p - py * W;
      area++;
      if (pxx < x0) x0 = pxx; if (pxx > x1) x1 = pxx;
      if (py < y0) y0 = py; if (py > y1) y1 = py;
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const nx = pxx + dx, ny = py + dy;
          if (nx < 0 || ny < 0 || nx >= W || ny >= H) continue;
          const q = ny * W + nx;
          if (mask[q] && lab[q] < 0) { lab[q] = id; stack.push(q); }
        }
      }
    }
    boxes.push({ x0, y0, x1, y1, w: x1 - x0 + 1, h: y1 - y0 + 1, area });
  }

  // -- bands, then frames within a band ------------------------------------
  const keep = boxes.filter((b) => b.h >= 28 && b.area >= 400).sort((a, b) => a.y0 - b.y0);
  const bands = [];
  for (const b of keep) {
    let hit = null;
    for (const bd of bands) {
      const ov = Math.min(bd.y1, b.y1) - Math.max(bd.y0, b.y0);
      if (ov > Math.min(bd.y1 - bd.y0, b.h) * 0.42) { hit = bd; break; }
    }
    if (hit) { hit.y0 = Math.min(hit.y0, b.y0); hit.y1 = Math.max(hit.y1, b.y1); hit.items.push(b); }
    else bands.push({ y0: b.y0, y1: b.y1, items: [b] });
  }
  bands.sort((a, b) => a.y0 - b.y0);

  const colSum = (x0, x1, y0, y1) => {
    let s = 0;
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) s += mask[y * W + x];
    return s;
  };

  const bandFrames = bands.map((bd) => {
    bd.items.sort((a, b) => a.x0 - b.x0);
    let frames = [];
    for (const it of bd.items) {
      const last = frames[frames.length - 1];
      if (last && it.x0 <= last.x1 + 6) {
        last.x1 = Math.max(last.x1, it.x1);
        last.y0 = Math.min(last.y0, it.y0);
        last.y1 = Math.max(last.y1, it.y1);
      } else frames.push({ x0: it.x0, x1: it.x1, y0: it.y0, y1: it.y1 });
    }
    // two sprites that touch read as one wide frame; cut them at the thinnest
    // column between them, and keep cutting while anything is still too wide
    const median = frames.map((f) => f.x1 - f.x0 + 1).sort((a, b) => a - b)[Math.floor(frames.length / 2)] || 80;
    for (let pass = 0; pass < 4; pass++) {
      const next = [];
      let cut = false;
      for (const f of frames) {
        const w = f.x1 - f.x0 + 1;
        if (w < median * 1.55) { next.push(f); continue; }
        const parts = Math.max(2, Math.round(w / median));
        const seg = w / parts;
        let bestX = -1, bestV = Infinity;
        const lo = f.x0 + Math.round(seg * 0.62), hi = f.x0 + Math.round(seg * 1.38);
        for (let x = lo; x <= Math.min(hi, f.x1 - 4); x++) {
          const v = colSum(x - 1, x + 1, f.y0, f.y1);
          if (v < bestV) { bestV = v; bestX = x; }
        }
        if (bestX < 0) { next.push(f); continue; }
        next.push({ x0: f.x0, x1: bestX - 1, y0: f.y0, y1: f.y1 });
        next.push({ x0: bestX + 1, x1: f.x1, y0: f.y0, y1: f.y1 });
        cut = true;
      }
      frames = next;
      if (!cut) break;
    }
    // retighten each cut frame to its real content
    for (const f of frames) {
      let nx0 = f.x1, nx1 = f.x0, ny0 = f.y1, ny1 = f.y0;
      for (let y = f.y0; y <= f.y1; y++) {
        for (let x = f.x0; x <= f.x1; x++) {
          if (!mask[y * W + x]) continue;
          if (x < nx0) nx0 = x; if (x > nx1) nx1 = x;
          if (y < ny0) ny0 = y; if (y > ny1) ny1 = y;
        }
      }
      if (nx0 <= nx1) { f.x0 = nx0; f.x1 = nx1; f.y0 = ny0; f.y1 = ny1; }
    }
    frames.sort((a, b) => a.x0 - b.x0);
    return { y0: bd.y0, y1: bd.y1, frames };
  });

  // -- scale so a standing body is `bodyH` tall -----------------------------
  const bodyRef = Math.max(...bandFrames[0].frames.map((f) => f.y1 - f.y0 + 1));
  const K = sheet.bodyH / bodyRef;

  // -- palette: median cut over everything that survives --------------------
  // the desert is already brown, so lift saturation and contrast a little on
  // the way in or the characters sink into their own background
  const punch = (r, g, b) => {
    const l = 0.299 * r + 0.587 * g + 0.114 * b;
    const sat = 1.22, con = 1.14, mid = 128;
    return [
      Math.max(0, Math.min(255, (l + (r - l) * sat - mid) * con + mid)),
      Math.max(0, Math.min(255, (l + (g - l) * sat - mid) * con + mid)),
      Math.max(0, Math.min(255, (l + (b - l) * sat - mid) * con + mid)),
    ];
  };
  const samples = [];
  for (let i = 0; i < W * H; i += 5) {
    if (!mask[i]) continue;
    samples.push(punch(d[i * 4], d[i * 4 + 1], d[i * 4 + 2]));
  }
  const palette = medianCut(samples, sheet.colors);

  // -- downsample every frame ----------------------------------------------
  const cells = [];
  sheet.bands.forEach((spec, bi) => {
    const bd = bandFrames[bi];
    if (!bd) return;
    let idx = 0;
    for (const [name, n] of spec) {
      for (let k = 0; k < n; k++) {
        const f = bd.frames[idx++];
        if (!f) continue;
        const isFace = sheet.faceBands.includes(bi);
        cells.push({ name, i: k, f, band: bd, isFace });
      }
    }
  });

  const shrunk = cells.map((c) => {
    const f = c.f;
    const sw = f.x1 - f.x0 + 1, sh = f.y1 - f.y0 + 1;
    const w = Math.max(1, Math.round(sw * K));
    const h = Math.max(1, Math.round(sh * K));
    const rgba = new Uint8ClampedArray(w * h * 4);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        // area average of the source box behind this destination pixel
        const ax0 = f.x0 + Math.floor((x * sw) / w), ax1 = f.x0 + Math.max(Math.floor(((x + 1) * sw) / w), Math.floor((x * sw) / w) + 1);
        const ay0 = f.y0 + Math.floor((y * sh) / h), ay1 = f.y0 + Math.max(Math.floor(((y + 1) * sh) / h), Math.floor((y * sh) / h) + 1);
        let r = 0, g = 0, b = 0, cov = 0, n = 0;
        for (let yy = ay0; yy < ay1; yy++) {
          for (let xx = ax0; xx < ax1; xx++) {
            const i = yy * W + xx;
            n++;
            if (!mask[i]) continue;
            cov++;
            r += d[i * 4]; g += d[i * 4 + 1]; b += d[i * 4 + 2];
          }
        }
        const o = (y * w + x) * 4;
        if (!cov || cov / n < 0.42) { rgba[o + 3] = 0; continue; }
        const col = nearest(palette, ...punch(r / cov, g / cov, b / cov));
        rgba[o] = col[0]; rgba[o + 1] = col[1]; rgba[o + 2] = col[2]; rgba[o + 3] = 255;
      }
    }
    // trim the transparent margin, keeping track of where the anchor went
    let tx0 = w, tx1 = -1, ty0 = h, ty1 = -1;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        if (!rgba[(y * w + x) * 4 + 3]) continue;
        if (x < tx0) tx0 = x; if (x > tx1) tx1 = x;
        if (y < ty0) ty0 = y; if (y > ty1) ty1 = y;
      }
    }
    if (tx1 < 0) { tx0 = 0; tx1 = 0; ty0 = 0; ty1 = 0; }
    const tw = tx1 - tx0 + 1, th = ty1 - ty0 + 1;
    const trimmed = new Uint8ClampedArray(tw * th * 4);
    for (let y = 0; y < th; y++) {
      for (let x = 0; x < tw; x++) {
        const s = ((y + ty0) * w + (x + tx0)) * 4, o = (y * tw + x) * 4;
        trimmed[o] = rgba[s]; trimmed[o + 1] = rgba[s + 1];
        trimmed[o + 2] = rgba[s + 2]; trimmed[o + 3] = rgba[s + 3];
      }
    }
    // faces anchor at their centre; bodies anchor on the band's ground line
    let ax = c.isFace ? Math.round(tw / 2) : Math.round(sw * K / 2) - tx0;
    let ay = c.isFace ? Math.round(th / 2) : Math.round((c.band.y1 - f.y0 + 1) * K) - ty0;

    // -- the outline ------------------------------------------------------
    // Every other thing in this game is drawn by a painter that puts a hard
    // dark line around its silhouette. A downsampled photograph of a drawing
    // has no such line, and without one she sits in front of the desert
    // instead of in it. So one gets added here, `outline` pixels thick, plus
    // a darkened rim just inside it so the edge has some weight.
    const OW = sheet.outline | 0;
    if (!OW) return { name: c.name, i: c.i, w: tw, h: th, ax, ay, rgba: trimmed };

    const pw = tw + OW * 2, ph = th + OW * 2;
    const out = new Uint8ClampedArray(pw * ph * 4);
    for (let y = 0; y < th; y++) {
      for (let x = 0; x < tw; x++) {
        const si = (y * tw + x) * 4, oi = ((y + OW) * pw + (x + OW)) * 4;
        out[oi] = trimmed[si]; out[oi + 1] = trimmed[si + 1];
        out[oi + 2] = trimmed[si + 2]; out[oi + 3] = trimmed[si + 3];
      }
    }
    // darken the pixels that sit on the silhouette
    const rim = sheet.rim ?? 0;
    if (rim) {
      const edge = [];
      for (let y = 0; y < ph; y++) {
        for (let x = 0; x < pw; x++) {
          const i = (y * pw + x) * 4;
          if (!out[i + 3]) continue;
          let open = false;
          for (let dy = -1; dy <= 1 && !open; dy++) {
            for (let dx = -1; dx <= 1; dx++) {
              const nx = x + dx, ny = y + dy;
              if (nx < 0 || ny < 0 || nx >= pw || ny >= ph || !out[(ny * pw + nx) * 4 + 3]) { open = true; break; }
            }
          }
          if (open) edge.push(i);
        }
      }
      for (const i of edge) {
        out[i] *= rim; out[i + 1] *= rim; out[i + 2] *= rim;
      }
    }
    // then grow the line outward from whatever is now opaque
    for (let pass = 0; pass < OW; pass++) {
      const add = [];
      for (let y = 0; y < ph; y++) {
        for (let x = 0; x < pw; x++) {
          const i = (y * pw + x) * 4;
          if (out[i + 3]) continue;
          let touch = false;
          for (let dy = -1; dy <= 1 && !touch; dy++) {
            for (let dx = -1; dx <= 1; dx++) {
              if (Math.abs(dx) + Math.abs(dy) === 2 && pass === 0) continue;  // rounder corners
              const nx = x + dx, ny = y + dy;
              if (nx < 0 || ny < 0 || nx >= pw || ny >= ph) continue;
              if (out[(ny * pw + nx) * 4 + 3]) { touch = true; break; }
            }
          }
          if (touch) add.push(i);
        }
      }
      for (const i of add) {
        out[i] = 18; out[i + 1] = 12; out[i + 2] = 8; out[i + 3] = 255;
      }
    }
    ax += OW; ay += OW;
    return { name: c.name, i: c.i, w: pw, h: ph, ax, ay, rgba: out };
  });

  // -- shelf pack -----------------------------------------------------------
  const order = shrunk.slice().sort((a, b) => b.h - a.h);
  const AW = 512;
  let cx = 1, cy = 1, rowH = 0;
  for (const s of order) {
    if (cx + s.w + 1 > AW) { cx = 1; cy += rowH + 1; rowH = 0; }
    s.x = cx; s.y = cy;
    cx += s.w + 1;
    rowH = Math.max(rowH, s.h);
  }
  const AH = cy + rowH + 1;
  const atlas = document.createElement('canvas');
  atlas.width = AW; atlas.height = AH;
  const ax2 = atlas.getContext('2d');
  for (const s of order) {
    const im = new ImageData(s.rgba, s.w, s.h);
    ax2.putImageData(im, s.x, s.y);
  }

  const frames = {};
  for (const s of shrunk) {
    (frames[s.name] ||= [])[s.i] = { x: s.x, y: s.y, w: s.w, h: s.h, ax: s.ax, ay: s.ay };
  }
  for (const k of Object.keys(frames)) frames[k] = frames[k].filter(Boolean);

  return { w: AW, h: AH, png: atlas.toDataURL('image/png'), frames, frameCount: shrunk.length };

  // -- helpers --------------------------------------------------------------
  function nearest(pal, r, g, b) {
    let bi = 0, bd = Infinity;
    for (let i = 0; i < pal.length; i++) {
      const dr = pal[i][0] - r, dg = pal[i][1] - g, db = pal[i][2] - b;
      const v = dr * dr * 0.90 + dg * dg * 1.76 + db * db * 0.34;
      if (v < bd) { bd = v; bi = i; }
    }
    return pal[bi];
  }

  function medianCut(pts, n) {
    let boxesP = [pts];
    while (boxesP.length < n) {
      let bi = -1, bs = -1;
      boxesP.forEach((bx, i) => { if (bx.length > bs) { bs = bx.length; bi = i; } });
      const bx = boxesP[bi];
      if (!bx || bx.length < 2) break;
      let ch = 0, bestR = -1;
      for (let c = 0; c < 3; c++) {
        let lo = 255, hi = 0;
        for (const p of bx) { if (p[c] < lo) lo = p[c]; if (p[c] > hi) hi = p[c]; }
        if (hi - lo > bestR) { bestR = hi - lo; ch = c; }
      }
      bx.sort((a, b) => a[ch] - b[ch]);
      const mid = bx.length >> 1;
      boxesP.splice(bi, 1, bx.slice(0, mid), bx.slice(mid));
    }
    return boxesP.filter((b) => b.length).map((b) => {
      let r = 0, g = 0, bl = 0;
      for (const p of b) { r += p[0]; g += p[1]; bl += p[2]; }
      return [Math.round(r / b.length), Math.round(g / b.length), Math.round(bl / b.length)];
    });
  }
}
